### ISSUE TITLE
Plugin (Permission Denied)

### ISSUE THREAD

**Issue by Nahuhacks** [mtoensing/Docker-Minecraft-PaperMC-Server#101]
.jar:git-Paper-318]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.Main.main(Main.java:134) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.Main.main(Main.java:325) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.io.FileNotFoundException: plugins/FastChunkPregenerator-2.0.9-SNAPSHOT.jar (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
        at java.io.RandomAccessFile.open(Unknown Source) ~[?:?]
        at java.io.RandomAccessFile.<init>(Unknown Source) ~[?:?]
        at java.io.RandomAccessFile.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$Source.get(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:?]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:51) ~[paper-1.20.2.jar:git-Paper-318]
        ... 20 more

Can someone help me?
This has never happened before.

**Comment by mtoensing** [comment]
Sorry I can’t give support for plugins.
