### ISSUE TITLE
Error: lost connection: Authentication servers are down. Please try again later, sorry!

### ISSUE THREAD

**Issue by partymaster64** [mtoensing/Docker-Minecraft-PaperMC-Server#83]
Hello

I keep having the following error while trying to connect to my server (container Logs): 

`_[18:03:55 INFO]: com.mojang.authlib.GameProfile@6425f0b9[id=<null>,name=Partymaster_888,properties={},legacy=false] (/192.168.1.1:54949) lost connection: Authentication servers are down. Please try again later, sorry!_`

When I first connected to the server after I deployed it, surprisingly I could join. But after the second reconnect I keep getting this error message. I tried disabling Online-Mode but it didn't solve it.

What is the issue and what do I need to do, to solve the problem?
Thank You very much!

**Full log:**

```
Starting org.bukkit.craftbukkit.Main
System Info: Java 20 (OpenJDK 64-Bit Server VM 20.0.1+9) Host: Linux 5.15.0-73-generic (amd64)
Loading libraries, please wait...
[18:02:48 INFO]: [STDERR]: You have used the Spigot command line EULA agreement flag.
[18:02:48 INFO]: [STDERR]: By using this setting you are indicating your agreement to Mojang's EULA (https://account.mojang.com/documents/minecraft_eula).
[18:02:48 INFO]: [STDERR]: If you do not agree to the above EULA please stop your server and remove this flag immediately.
[18:02:48 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:02:50 INFO]: Loaded 7 recipes
[18:02:51 INFO]: Starting minecraft server version 1.19.4
[18:02:51 INFO]: Loading properties
[18:02:51 INFO]: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
[18:02:51 INFO]: Server Ping Player Sample Count: 12
[18:02:51 INFO]: Using 4 threads for Netty based IO
[18:02:52 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[18:02:52 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[18:02:52 INFO]: Default game type: SURVIVAL
[18:02:52 INFO]: Generating keypair
>....
[18:02:52 INFO]: Starting Minecraft server on *:25565
>....
[18:02:52 INFO]: Using epoll channel type
>....
[18:02:52 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
>....
[18:02:52 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
>....
[18:02:52 INFO]: Server permissions file permissions.yml is empty, ignoring it
>....
[18:02:52 INFO]: Preparing level "world"
>....
[18:02:53 INFO]: Preparing start region for dimension minecraft:overworld
>....
[18:02:53 INFO]: Time elapsed: 218 ms
>....
[18:02:53 INFO]: Preparing start region for dimension minecraft:the_nether
>....
[18:02:53 INFO]: Time elapsed: 140 ms
>....
[18:02:53 INFO]: Preparing start region for dimension minecraft:the_end
>....
[18:02:53 INFO]: Time elapsed: 107 ms
>....
[18:02:53 INFO]: Running delayed init tasks
>....
[18:02:53 INFO]: Done (2.066s)! For help, type "help"
>....
[18:02:53 INFO]: Timings Reset
>....
[18:03:55 INFO]: Disconnecting com.mojang.authlib.GameProfile@6425f0b9[id=<null>,name=Partymaster_888,properties={},legacy=false] (/192.168.1.1:54949): Authentication servers are down. Please try again later, sorry!
>....
[18:03:55 ERROR]: Couldn't verify username because servers are unavailable
>....
[18:03:55 INFO]: com.mojang.authlib.GameProfile@6425f0b9[id=<null>,name=Partymaster_888,properties={},legacy=false] (/192.168.1.1:54949) lost connection: Authentication servers are down. Please try again later, sorry!

```

**Comment by exibyte** [comment]
Hey OP,
Are you by any chance using a docker-pihole or docker-adguard?
I have the same Problem when using the adguard as the primary-dns for my network.
I set it as dns for the internal-network in my fritz-box and I am no longer able to connect or rerun the docker-run script.
It stucks at "piston-data.mojang.com" during download of 1.20.1jar file

Before I started over I got the same error as op.
For me it defitenately works when disabling adguard.
But that shouldn't be the solution.

Adguard is also a docker-container on the same rpi.
The url is not blocked. (Well, at least they are listed as "allowed" in adguard)

Is there a way to tell the docker-container for minecraft to use a different dns?
All my other tools (e.g. a bitwarden in docker) work fine.

The only error i have is this:

Downloading mojang_1.20.1.jar
Failed to download mojang_1.20.1.jar
java.net.UnknownHostException: piston-data.mojang.com
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at java.base/java.net.URL.openStream(Unknown Source)
        at io.papermc.paperclip.DownloadContext.download(DownloadContext.java:55)
        at io.papermc.paperclip.Paperclip.setupClasspath(Paperclip.java:63)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:28)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at io.papermc.paperclip.Main.main(Main.java:26)
